language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: VFTkZ4x/5cPGdI91XVnGfH7Se3jwDgh2b0KkFCBabs4zUpOXkPSz621+ebHVr+znH6t+4Jd0wN5WeBmCeiSHZw2clqq5wmwomeVJGaApt6I0INmwTTpDZwr9l/ZlphbCLdR4tH78meeEjTw+u32kBJQvYCGhy0g3zaXLo+QSs/PbSXb/onIM2/8l2+QraVuWthpe2kcXjH6QPIc4m+0vAGCBpi+OJ0mYbvZYT5sNZ6AicZ3U8s19rGTgY3cCB3DLZKOsVAvqB3ldz3YuxpC1WHVOPC/hOkO0gQGYgnNQEiB2HoKl1+dsoZc3BrDi7XrkHJs3vN8d7+CwgW2XCDGq83EA79Ox9DxFKhANNtRDckKXzkWZsqeW4INk5Z+kj1hgj3UHqe6eQh/Fn+EUpbfAbNcFKLHQQ8AdYTbx5EmbFw1DVbWx/PAYcHXxrG2czuzYwd/y50x+q8bXfugyBMVDGcDAjn/Msx3kq4gGk29cwC5EcTiXLkS83n+vYja2aQPdDM5+EtG9CIW5wxyxk4E7N7aXuGfuh/1mfv2WdF7HiQAwTxygM9yxzIH1ZZvVUHI0OZ6uUckbt6UmZUWs+d5W5zut1qEjpzZzO11tTIf9LeifUz9UH1Qh622+/1q2eEuG2AhK/SmJofwHRfO54UuiaZfjdXJLVIRzU7n8kHpiww0=
  - secure: nCBzLoR2Xg8zalQFxbcy+x/F2J9Wx/wgPDBthh2myGJmQ3V9rgJSGk+4CZoJtGqKQutRhmuSusQ9HRK689XxoTseWkPo44bTqC96G1FPd/o2tC2F2JA0q+oVN78krzn+hFFlWdgvOfgIW8Y5Gbb59PMey+TnpIZnz9UA6N39y4xA6igh8pLOYIZYEmqu2q1laKBHIM+lOWYIAAHwrmaZPfelt3JO+PnRr7/HRR0caqZ1JOorLpByDr4kMYvh02ynd/ubmoQjkeUqg5+AMBg79A5itSHsk1jZZFfl4Oe0GdXGl1D5KrcLp1WLKFbNAH8p+AnjhYbvyaB2rzK3s5KenT+EqdFiTqlgY1pR3A3mWmq8wtqULRzgGRx0/Tvd+CnE+IUn1cJo1h+BFt62ZEfQ6ukMiKBlsxtbNsq4Bgo80HhILYrzNpmBMZCg1fJ+R2JBGF5x7o+c7kiOgbUiDdTeiUNtYnydPBrrtX1knUMQBM5fmjSkoIyo1kwrwUxi1r3khcmDvL7USXNKwWj71mS02Fsz2+FoAbfFk7johlcWHwLXkFVkhOA0ScaARSaKy+n2sQNXqyVvZZcAmzq4Zg8GaIwoWVWZZ4GyI8xktE9NJdu3zBiBqN+fXrDoXhapeOMSQMZSyEUmWnV33+t4AYobRVKJwfvCoBuE3n5XTtxOMPo=
  matrix:
  - SCC_DOCKER_IMAGE=anthonydenecheau/scc-enci-judge-service:version1.0
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $SCC_DOCKER_IMAGE
