#Default port is 8092
server:
  port: 8092
  
spring:
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
                
#Setting the logging levels for the service
#Migrate to logstach and Cloud Config
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.scc: DEBUG      